import java.time.ZonedDateTime

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

val appName = "JavaSandbox"
val buildBasename = "jsandbox"
val buildVersion = Version.makeVersionString()

plugins {
    id("project.java-application-conventions")
}

dependencies {}

application {
    mainClass.set("javasandbox.Main")
    mainModule.set("javasandbox")

    applicationName = appName
    executableDir = ""

    // Include '$projectDir/data' directory in archive files of the distribution task.
    // applicationDistribution.into("data") {
    //     from("data")
    // }
}

// Another way to include the '$projectDir/data' directory.
// distributions.main.get().contents.into("data") {
//     from("data")
// }

tasks.register<WriteProperties>("processResources_buildProperties") {
    description = "Creates a properties file containing the build information."

    outputFile = File(sourceSets.main.get().output.resourcesDir, "build.properties")
    property("build.date", ZonedDateTime.now().withNano(0))
    property("build.version", buildVersion)
}

tasks.processResources {
    dependsOn(tasks.named("processResources_buildProperties"))
}

tasks.jar {
    manifest {
        attributes["Implementation-Version"] = buildVersion
        attributes["Main-Class"] = application.mainClass.get()
    }

    archiveBaseName.set(buildBasename)
    archiveVersion.set(buildVersion)
}
