/*
 * This source file was generated by the Gradle 'init' task
 */
package javasandbox;

import java.nio.charset.Charset;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // String fileEncoding = System.getProperty("file.encoding");
        String fileEncoding = Charset.defaultCharset().displayName();

        System.out.printf("file.encoding = %s%n", fileEncoding);
    }
}
