/*
 * This source file was generated by the Gradle 'init' task
 */
package javasandbox;

import java.nio.charset.Charset;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    void main(String[] args) {
        System.out.println(new App().getGreeting());

        String javaVersion = System.getProperty("java.version");
        System.out.printf("java.version = %s%n", javaVersion);

        // String javaRuntimeVersion = System.getProperty("java.runtime.version");
        String javaRuntimeVersion = Runtime.version().toString();
        System.out.printf("java.runtime.version = %s%n", javaRuntimeVersion);

        String javafxRuntimeVersion = System.getProperty("javafx.runtime.version");
        System.out.printf("javafx.runtime.version = %s%n", javafxRuntimeVersion);

        // String fileEncoding = System.getProperty("file.encoding");
        String fileEncoding = Charset.defaultCharset().displayName();
        System.out.printf("file.encoding = %s%n", fileEncoding);
    }
}
